/*** Auth ***/
export const AUTH_REQUEST_START = 'AUTH_REQUEST_START';
export const AUTH_REQUEST_SUCCESS = 'AUTH_REQUEST_SUCCESS';
export const AUTH_REQUEST_FAILURE = 'AUTH_REQUEST_FAILURE';

export const SET_FOOTER_TAB = 'SET_FOOTER_TAB';
